vocab.levelThreeDayOne = {
  day: 'Level Three Day One',
  1: ['dʉ̂an mókkarāa khōm', 'duan mokkaraa khom', 'january'],
  2: ['dʉ̂an kūmphāa phān', 'duan kumphaa phan', 'february'],
  3: ['dʉ̂an mīināa khōm', 'duan miinaa khom', 'march'],
  4: ['dʉ̂an mēesǎa yōn', 'duan meesaa yon', 'april'],
  5: ['dʉ̂an phrʉ́tsaphāa khōm', 'duan phrutsaphaa khom', 'may'],
  6: ['dʉ̂an míthùnāa yōn', 'duan mithunaa yon', 'june'],
  7: ['dʉ̂an karákkadāa khōm', 'duan karakkadaa khom', 'july'],
  8: ['dʉ̂an sǐŋhǎa khōm', 'duan singhaa khom', 'august'],
  9: ['dʉ̂an kānyāa yōn', 'duan kanyaa yon', 'september'],
  10: ['dʉ̂an tùlāa khōm', 'duan tulaa khom', 'october'],
  11: ['dʉ̂an phrʉ́tsacikāa yōn', 'duan phrutsacikaa yon', 'november'],
  12: ['dʉ̂an thānwāa khōm', 'duan thanwaa khom', 'december'],
  13: ['rʉ́dūu rɔ́ɔn', 'ruduu roon', 'summer'],
  14: ['rʉ́dūu fǒn', 'ruduu fon', 'rainy season'],
  15: ['rʉ́dūu nǎaw', 'ruduu naaw', 'winter'],
  16: ['rʉ́dūu bāymáayrûaŋ', 'ruduu baymaayruang', 'autumn'],
  17: ['rʉ́dūu bāymáayphlì', 'ruduu baymaayphli', 'spring'],
  18: ['thāmhây', 'thamhay', 'to cause, make'],
  19: ['pēnwàt', 'penwat', 'have a cold'],
  20: ['mákca', 'makca', 'usually, often'],
  21: ['rót tìt', 'rot tit', 'the traffic jam'],
  22: ['talɔ̀ɔt', 'taloot', 'all through, all'],
  23: ['himá', 'hima', 'snow'],
  24: ['khɔ̂nkhâaŋ', 'khonkhaang', 'rather'],
  25: ['fáa rɔ́ɔŋ', 'faa roong', 'thunder (noise, sound)'],
  26: ['fáa lɜ́p', 'faa lep', 'lightning (flash of lightning)'],
  27: ['fáa phàa', 'faa phaa', 'thunderbolt (strike of lightning)'],
  28: ['rɔ́ɔŋhâay', 'roonghaay', 'to cry'],
  29: ['náam thûam', 'naam thuam', 'flood'],
  30: ['chə̀chɛ̀', 'cheche', 'to be wet, damp'],
  31: ['lʉ̂ʉn', 'luun', 'to slip'],
  32: ['lāmbàak', 'lambaak', 'to be in trouble, become poverty-stricken'],
  33: ['rôm', 'rom', 'umbrella'],

};

vocab.levelThreeDayTwo = {
  day: 'Level Three Day Two',
  1: ['sá́k', 'sak', 'just, as little as'],
  2: ['tâŋ', 'tang', 'as many as, as much as'],
  3: ['khɛ̂ɛ', 'khee', 'only'],
  4: ['khɛ̂ɛníi', 'kheenii', 'only this much'],
  5: ['athíbāay', 'athibaay', 'to explain'],
  6: ['sùk', 'suk', 'to be ripe'],
  7: ['dìp', 'dip', 'to be raw, or underripe'],
  8: ['plìan', 'plian', 'to change'],
  9: ['prachūm', 'prachum', 'meeting, to have a meeting'],
  10: ['lʉ̂ak', 'luak', 'to choose, select'],
  11: ['sòt', 'sot', 'to be fresh'],
  12: ['pramāan', 'pramaan', 'about, estimate, approximate'],
  13: ['mamûaŋ', 'mamuang', 'mango'],
  14: ['faràŋ', 'farang', 'guava'],
  15: ['prîaw', 'priaw', 'to be sour'],
  16: ['wǎan', 'waan', 'to be sweet'],
  17: ['khēm', 'khem', 'to be salty'],
  18: ['khǒm', 'khom', 'to be bitter'],
};


vocab.levelThreeDayThree = {
  day: 'Level Three Day Three',
  1: ['phə̂ŋ', 'pheng', 'just, just now'],
  2: ['phɔ̄ɔ ca... dâay', 'phoo ca... daay', 'be able to do it (guess, not sure)'],
  3: ['khɔ̂nkhâaŋ', 'khonkhaang', 'rather'],
  4: ['prayòok', 'prayook', 'sentence'],
  5: ['lóm', 'lom', 'to fall down (from an upright position)'],
  6: ['cèp', 'cep', 'be pained, hurt'],
  7: ['phayāayāam', 'phayaayam', 'to try'],
  8: ['hǎay', 'haay', 'to recover, be lost'],
  9: ['phák', 'phak', 'to rest, take a break'],
  10: ['thām khwāam-sa ' + "'" + 'àat', 'tham khwaam-sa at', 'to clean'],
  11: ['chét', 'chet', 'to wipe']
};
vocab.levelThreeDayFour = {
  day: 'Level Three Day Four',
  1: ['sabùu', 'sabuu', 'soap'],
  2: ['chɛ̄ɛmphūu', 'cheemphuu', 'shampoo'],
  3: ['prɛ̄ɛŋsǐifān', 'preengsiifan', 'toothbrush'],
  4: ['yāasǐifāan', 'yaasiifan', 'toothpaste'],
  5: ['khrīim-kōon-nùat', 'khriim koon nuat', 'shaving cream'],
  6: ['kʉ̀ap ca', 'kuap ca', 'almost'],
  7: ['mòt', 'mot', 'be used up, it' + "'" + 's all gone'],
  8: ['cháy', 'chay', 'to use'],
  9: ['pîŋ (khanǒmpāŋ)', 'ping khanompang', 'to toast'],
  10: ['khrʉ̂aŋ pîŋ khanǒmpāŋ', 'khruang ping phanompang', 'toaster'],
  11: ['plìan', 'plian', 'to change'],
  12: ['thîinɔ̄ɔn', 'thiinoon', 'mattress'],
  13: ['pūu (thîinɔ̄ɔn)', 'puu thiinoon', 'to make a bed, to spread over'],
  14: ['phâa-pūu-thîinɔ̄ɔn', 'phaa puu thiinoon', 'sheet'],
  15: ['sákphâa', 'sakphaa', 'to wash clothes'],
  16: ['rîitphâa', 'riitphaa', 'to iron clothes'],
  17: ['khrʉ̂aŋ-sákphâa', 'khruang sakphaa', 'washing machine'],
  18: ['yɔ̀ɔt rǐan', 'yoot rian', 'to put a coin (in a machine)'],
  19: ['ráan-sákrîit', 'raan sakriit', 'laundry'],
  20: ['phâa-hòm', 'phaa hom', 'blanket'],
  21: ['plɔ̀ɔk-mɔ̌ɔn', 'plook moon', 'pillow case'],
};

vocab.levelThreeDayFive = {
  day: 'Level Three Day Five',
  1: ['châaŋ', 'chaang', 'technician, mechanic, specialist'],
  2: ['sɔ́ɔm', 'soom', 'to repair'],
  3: ['tûuyēn', 'tuuyen', 'refrigerator'],
  4: ['(thōo) pāy tāam ___', 'thoo pay taam', 'to call, send for someone'],
  5: ['kl̄ua', 'klua', 'to be afraid'],
  6: ['phátlōm', 'phatlom', 'fan'],
  7: ["'" + 'ɛɛ (khrʉaŋ' + "'" + 'ɛɛ)', 'ee khruang ee', 'air conditioner'],
  8: ['fāy dàp', 'fay dap', 'blackout, power failure'],
  9: ['rûa', 'rua', 'to (have a)leak'],
  10: ["'" + 'āntarāay', 'antaraay', 'to be dangerous'],
  11: ['rūam', 'ruam', 'to include, add'],
  12: ['tháŋmòt', 'thangmot', 'altogether'],
  13: ['khâa bɔ̄ɔrikāan', 'khaa boorikaan', 'service charge'],
  14: ['khâa châw (hɔ̂ŋ)', 'khaa chow hong', 'rental fee'],
  15: ['châw', 'chaw', 'to rent'],
  16: ['khâa-náam', 'khaa naam', 'water supply fee'],
  17: ['khâa-fāy', 'khaa fay', 'electricity bill'],
  18: ['pānhǎa', 'panhaa', 'problem'],
  19: ['(náam) lǎy', 'naam lay', 'to flow, run'],
};
vocab.levelThreeDaySix = {
  day: 'Level Three Day Six',
  1: ['thɛ̄ɛw níi', 'theew nii', 'this area'],
  2: ['pám, pámnámmān', 'pam, pamnamman', 'gas station'],
  3: ['sathǎanīi khǒnsòŋ', 'sathanii khonsong', 'transport station, bus terminal'],
  4: ['(yùu) lə̄əy', 'yuu looy', 'to be beyond, onward, further'],
  5: ['saphāan', 'saphaan', 'bridge'],
  6: ['saphāanlɔ̄ɔy', 'saphaanlooy', 'flyover, overpass, overcrossing, footbridge'],
  7: ['trōŋ níi', 'trong nii', 'right over here'],
  8: ['(də̄ən) pāy tāam ___', 'deen pay taam', 'to walk along__ (e.g. a street)'],
  9: ['khâam', 'khaam', 'to cross'],
  10: ['trōŋ (kān) khâam kàp', 'trong kan khaam kap', 'be opposite'],
  11: ['tit (kān) kàp', 'tit kan kap', 'to be adjecent to, connected'],
  12: ['rāwàaŋ___kàp___', 'rawaang kap', 'between'],
  13: ['pâay', 'paay', 'sign, poster, placard'],
  14: ['pàak sɔ̄ɔy', 'paak sooy', 'entrance to the soi'],
  15: ['sùt sɔ̄ɔy', 'sut sooy', 'end of the soi'],
  16: ["'" + 'anúsǎawārīi (chāy)', "'" + 'anusaawarii chay', 'monument (Victory Monument)'],
  17: ['sì', 'si', 'particle indicating definiteness or emphasis'],
};

vocab.levelThreeDaySeven = {
  day: 'Level Three Day Seven',
  1: ['dâyráp', 'dayrap', 'to receive'],
  2: ['bàtchə̄ən', 'batcheen', 'invitation card'],
  3: ['ŋāan', 'ngaan', '1. work, task job 2. ceremony, festival, affair'],
  4: ['tɛ̀ŋŋāan', 'tengngaan', 'to marry, get married'],
  5: ['ŋāantɛ̀ŋŋāan', 'ngaantengngaan', 'wedding'],
  6: ['sòp', 'sop', 'corpse (n)'],
  7: ['ŋāansòp', 'ngaansop', 'funeral'],
  8: ['câwbàaw', 'cawbaaw', 'groom'],
  9: ['câwsǎaw', 'cawsaaw', 'bride'],
  10: ['rótnáam', 'rotnaam', 'to ppour water on'],
  11: ['suphâap', 'suphaap', 'be polite'],
  12: ["'ūayphɔ̄ɔn", 'uayphoon', 'to bless, wish (someone well)'],
  13: ['khɔ̌ɔhây___', 'khoohay', 'May you be... Wish you...'],
  14: ['khwāamsùk', 'khwaamsuk', 'happiness'],
  15: ['tɛ̀ŋtūa', 'tengtua', 'to dress'],
  16: ['ŋāankhʉ̂nbâanmày', 'ngaankhunbaanmay', 'a housewarming'],
  17: ['câwphâap', 'cawphaap', 'host, hostess'],
  18: ['thām-būn', 'tham-bun', 'to make merit'],
};

vocab.levelThreeDayEight = {
  day: 'Level Three Day Eight',
  1: ['tɔ̂ŋkāan', 'tengkaan', 'to need, want, require'],
  2: ['bānchīi', 'banchii', 'account, bank account'],
  3: ['tìttɔ̀ɔ', 'tittoo', 'to contact'],
  4: ['bāy-khàpkhìi', 'bay-khapkhii', 'driver license'],
  5: ['bɛ̀ɛpfɔ̄ɔm', 'beepfoom', 'the form'],
  6: ['krɔ̀ɔk bɛ̀ɛpfɔ̄ɔm', 'krook beepfoom', 'to fill the form'],
  7: ['bàt-prachàachōn', 'bat-prachaachon', 'ID card'],
  8: ["'èekkasǎan", 'eekkasaan', 'document'],
  9: ["thàay 'èekkasǎan", 'thaay eekkasaan', 'to photocopy'],
  10: ["mòt 'āayu", 'mot aayu', 'to expire'],
  11: ["tɔ̀ɔ 'āayu", 'too aayu', 'to renew, extend'],
  12: ["bāy- 'anúyâat-thāmŋāan", 'bay anuyaat thamngaan', 'work permit'],
  13: ['thùuk...', 'thuuk', 'element used in making passive voice sentence'],
  14: ['(sɔ̌ɔ.) tɔ̄ɔ.mɔ̄ɔ.', 'soo too moo', 'immigration division'],
  15: ['(sǎmnákŋāan trùat khōn khâw mʉ̄aŋ)', 'samnakngaan truat khon khaw muang', '???'],
  16: ['pràp', 'prap', 'to fine'],
  17: ['khamōoy', 'khamooy', 'to steal, a thief'],
  18: ['càp', 'cap', 'to catch, arrest'],
  19: ['khōnráay', 'khonraay', 'criminal, outlaw, gangsters'],
  20: ['sathǎanīi-tāmruàt', 'sathaanii tamruat', 'police station'],
  21: ['càay', 'caay', 'to pay'],
  22: ['rûupthàay', 'ruupthaay', 'photo picture'],
};

vocab.levelThreeDayNine = {
  day: 'Level Three Day Nine',
  1: ['sàsǒm', 'sasom', 'to collect, store, accumulate'],
  2: ['phə̂ŋ', 'pheng', 'just'],
  3: ['rə̂əm', 'reem', 'to begin, start'],
  4: ['tháŋ...lɛ́...', 'thang...le...', 'both... and...'],
  5: ['nɔ̂ɔkcàak', 'nookcaak', 'besides, in the bargain, over and above'],
  6: ['bát-thōorasàp', 'bat-thoorasap', 'phone card'],
  7: ['líaŋ sàt', 'liang sat', 'to raise, breed animals'],
  8: ['nók', 'nok', 'bird'],
  9: ['khǒn nók', 'khon nok', 'feather, hair'],
  10: ['phɛ́ɛ', 'phee', 'be allergic'],
  11: ['lə̂ək', 'leek', 'to stop, discontinue, break up, give up'],
  12: ['dōoychaphɔ́', 'dooychapho', 'especially'],
  13: ['chūan', 'chuan', 'to persuade, invite'],
};

vocab.levelThreeDayEleven = {
  day: 'Level Three Day Eleven',
  1: ['sùanyày, sùanmâak', 'suanyay, suanmaak', 'majority'],
  2: ["'āachîip", 'aachiip', 'occupation'],
  3: ['nāa (khâaw)', 'naa (khaaw)', 'paddy field, rice field'],
  4: ['sǔan', 'suan', 'garden, orchard, plantation'],
  5: ['rây', 'ray', 'farm, crop-farming'],
  6: ['thām-nāa', 'tham-naa/suan/ray', 'to work in the naa, suan, ray'],
  7: ['chāawprāmōŋ', 'chaawpramong', 'fisherman'],
  8: ['líaŋsàt', 'liangsat', 'to raise, breed animals'],
  9: ['sǎmkhān', 'samkhan', 'be important'],
  10: ['nákthúrakìt', 'nakthurakit', 'businessman'],
  11: ['phanákŋāan', 'phanakngaan', 'staff'],
  12: ['hɛ̂ɛŋlɛ́ɛŋ', 'heengleeng', 'to dry, be arid'],
  13: ['plùuk', 'pluuk', 'to grow, plant'],
  14: ['khâaw hɔ̌ɔm mali', 'khaaw hoom mali', 'Thai jasmine rice'],
  15: ['pàamáay', 'paamaay', 'forest'],
  16: ['sʉ̌a', 'sua', 'tiger'],
};

vocab.levelThreeDayTwelve = {
  day: 'Level Three Day Twelve',
  1: ['thāhǎan', 'thahaan', 'military person, soldier'],
  2: ['tāmrùat', 'tamruat', 'policeman'],
  3: ['phāyāabāan', 'phayaabaan', 'nurse'],
  4: ["'āacāan", 'aacaan', 'professor, teacher (used in university etc.)'],
  5: ['nák rɔ́ɔŋ', 'nak roong', 'an expert in, someone having professional skill in'],
  6: ['nákkīilāa', 'nakkiilaa', 'athlete'],
  7: ['nákbīn', 'nakbin', 'pilot'],
  8: ['nákdōntrīi', 'nakdontrii', 'musician'],
  9: ['nákkhǐan', 'nakkhian', 'writer, author'],
  10: ['châŋ máay', 'chang maay', 'craftsman, technician, artisan, (a person doing work demanding manual skill)'],
  11: ['thʉ̌ŋmɛ́ɛwâa', 'thungmeewaa', 'even though'],
  12: ['khɔ̂nkhâaŋ', 'khonkhaang', 'rather'],
  13: ["'āntarāay", 'antaraay', 'be dangerous, risk'],
  14: ['māhǎawítthayāalāy', 'mahaawitthayaalay', 'university'],
  15: ['dūu mʉ̌an wâa', 'duu muan waa', 'seem, seems like'],
  16: ['phûak', 'phuak', 'group'],
  17: ['mīi chʉ̂ʉsǐaŋ', 'mii chuusiang', 'be famous'],
  18: ['ŋə̄ndʉ̄an', 'ngenduan', 'salary'],
};

vocab.levelThreeDayThirteen = {
  day: 'Level Three Day Thirteen',
  1: ['sì', 'si', 'particle indicating definiteness or emphasis'],
  2: ['yîam', 'yiam', 'to visit'],
  3: ['talàat-náam', 'talaat-naam', 'floating market'],
  4: ['wɛ́', 'we', 'to drop in, to make a side trip'],
  5: ['phákrɔ́ɔn', 'phakroon', 'have a vacation, vacation'],
  6: ['cɔ̄ɔŋ tǔa', 'coong tua', 'to reserve, book'],
  7: ['lûaŋnâa', 'luangnaa', 'in advance, previously, beforehand'],
  8: ['chūan', 'chuan', 'to persuade, invite'],
  9: ['sanùk', 'sanuk', 'be fun, funny, enjoy'],
  10: ['khɛ̀ɛk', 'kheek', 'guest, customer'],
  11: ['bɔ̄ɔrikāan', 'boorikaan', 'service'],
  12: ["kɔ̀' samǔy", 'ko samui', 'Samui Island'],
  13: ['wâaŋ', 'waang', 'be free, nothing to do, empty'],
  14: ['thān', 'than', 'to be in time, catch up with'],
  15: ['yə́', 'ye', 'lots, much, many']
};

vocab.levelThreeDayFourteen = {
  day: 'Level Three Day Fourteen',
  1: ['cāydīi', 'caydii', 'be kind, kind-hearted'],
  2: ['cāyrɔ́ɔn', 'cayroon', 'be hasty, impatience, hot-tempered'],
  3: ['cāyyēn', 'cayyen', 'be calm, patience'],
  4: ['mōohǒo', 'moohoo', "be cross, angry, lose one's temper"],
  5: ['khíi mōhǒo', 'khii moohoo', 'easily become angry, be resentful, fractious'],
  6: ['kròot', 'kroot', 'be angry'],
  7: ['câwnāay', 'cawnaay', 'boss, employer'],
  8: ['lûuknɔ́ɔŋ', 'luuknoong', 'subordinate'],
  9: ['thâwthîi hěn', 'thawthii hen', 'as far as'],
  10: ['tāamcāy', 'taamcay', 'to follow the wishes of, please, yield to the desire of'],
  11: ["'āay (khîi 'āay)", 'aay (khii aay)', 'be shy'],
  12: ['bòn (khîi bòn)', 'bon (khii bon)', 'to complain, mutter, grumble'],
  13: ['ŋùtŋìt (khîi ŋùtŋìt)', 'ngutngit (khii ngutngit)', 'be irritable, moody, bad tempered'],
  14: ['sadɛ̄ɛŋ', 'sadeeng', 'to show'],
  15: ["'āarōm", 'aarom', 'mood, temper'],
  16: ['klûmcāy', 'klumcay', 'to worry, be worried, to feel depressed'],
  17: ['khâwkān dâay', 'khawkan daay', 'to get along with'],
  18: ['pēnhùaŋ', 'penhuang', 'to worry, be worried, to feel concern for'],
  19: ['cûucîi', 'cuucii', 'be fussy'],
  20: ['suphâap', 'suphaap', 'be polite']
};

vocab.levelThreeDayFifteen = {
  day: 'Level Three Day Fifteen',
  1: ['khə̄əychīn', 'kheeychin', 'to get used to'],
  2: ['pràptūa', 'praptua', 'to adjust'],
  3: ['yîŋ...', 'ying...', 'the more...'],
  4: ['tāa ka yāay', 'taa ka yaay', 'grandfather grandmother (mother' + "'" + 's)'],
  5: ['pùu ka yâa', 'puu ka yaa', 'grandfather grandmother (father' + "'" + 's)'],
  6: ['phə̂ŋ', 'pheng', 'just'],
  7: ['nɛ̂ɛcāy', 'neecay', 'be sure'],
  8: ['bɔ̄ɔrisàt', 'boorisat', 'company'],
  9: ['prachūm', 'prachum', 'meeting'],
  10: ["'āahǎanthalēe", 'aahaanthalee', 'seafood'],
  11: ['bāaŋpūu', 'baangpuu', 'a district in Samutprakan'],
  12: ['yàakhây', 'yaakhay', 'to want, wish'],
  13: ['khwāamsùk', 'khwaamsuk', 'happiness'],
  14: ['khâw kàp...dâay', 'khaw kap...daay', 'to get along with...'],
  15: ['plɔ̀ɔtphāy', 'plootphay', 'be safe, out of danger']
};

vocab.levelThreeDaySixteen = {
  day: 'Level Three Day Sixteen',
  1: ['khɔ̂yyāŋchûa', 'khoyyangchua', 'to improve, get better'],
  2: ['hǎay...(lɛ́ɛw)', 'haay...(leew)', 'to recover, become healed'],
  3: ['hâam', 'haam', 'to forbid'],
  4: ["'anúyâat", 'anuyaat', 'to allow'],
  5: ['hěn cā tɔ̂ŋ klàp', 'hen ca tong klap', 'I think It' + "'" + 's time to go now'],
  6: ["'ɔ̀ɔk kāmlāŋ", 'ook kamlang', 'to exercise'],
  7: ['būrìi', 'burii', 'cigarette'],
  8: ['sùup būrìi', 'suup burii', 'to smoke a cigarette'],
  9: ['cèp', 'cep', 'hurt, to be in pain'],
  10: ['phlɛ̌ɛ', 'phlee', 'wound'],
  11: ["'āy", 'ay', 'to cough'],
  12: ['tāam pòkkāti', 'taam pokkati', 'normally, ordinarily, as usual'],
  13: ['lâw', 'law', 'liquor'],
  14: ['kīn lâw', 'kin law', 'to drink (liquor)'],
  15: ['lāa (kɔ̀ɔn)', 'laa (koon)', 'goodbye'],
  16: ['khɛ̌ŋrɛ̄ɛŋ', 'khengreeng', 'to be strong, powerful'],
};

vocab.levelThreeDaySeventeen = {
  day: 'Level Three Day Seventeen',
  1: ['nâa + verb = adj.', 'naa + verb = adj', 'bound stem placed in front of verbs to make new word: ...able, ...ing'],
  2: ['nâaràk', 'naarak', 'be loveable, lovely, cute'],
  3: ['nâathāan', 'naathaan', 'to be tasty-looking'],
  4: ['nâayùu', 'naayuu', 'be cozy, livable'],
  5: ['nâasʉ́ʉ', 'naasuu', 'interesting to buy'],
  6: ['nâasǒncāy', 'naasoncay', 'be interesting'],
  7: ['bɛ̀ɛp', 'beep', 'style, pattern'],
  8: ["clf. + 'ʉ̀ʉn", 'clf + uun', 'other, others, another'],
  9: ['yàaŋ ' + "'" + 'ʉ̀ʉn', 'yaang ' + "'" + 'uun', 'else, others'],
  10: ['yàa phə̂ŋ', 'yaa pheng', 'Don' + "'" + 't...yet (wait)']
};

vocab.levelThreeDayEighteen = {
  day: 'Level Three Day Eighteen',
  1: ['nǎŋ', 'nang', 'movie, film'],
  2: ['nǎŋ rʉ̂aŋ', 'nang ruang', 'name of movie'],
  3: ['nǎŋ phǐi', 'nang phii', 'ghost, horror movie'],
  4: ['nǎŋ tālòk', 'nang talok', 'comedy'],
  5: ['nǎŋ chīiwít', 'nang chiiwit', 'dramatic movie'],
  6: ['rōoŋ nǎŋ', 'roong nang', 'cinema, theatre'],
  7: ['mây rúu rʉ̂aŋ', 'may ruu ruang', 'do not understand'],
  8: ['thâa ŋán', 'thaa ngan', 'in case that, if so'],
  9: ['ráprɔ̄ɔŋ', 'raproong', 'to guarantee, ensure'],
  10: ['prachūm', 'prachum', 'to meet (in a group), to hold a meeting, meeting'],
  11: ['nâabʉ̀a', 'naabua', 'be boring']
};

vocab.levelThreeDayNineteen = {
  day: 'Level Three Day Nineteen',
  1: ['khɔ̌ŋcháay', 'khongchaay', 'appliance, utensils'],
  2: ['khrʉ̂aŋcháyfāyfáa (khrʉ̂aŋfāyfáa)', 'khruangchayfayfaa (khruangfayfaa)', 'electric appliance'],
  3: ['thāmdûay', 'thamduay', 'to be made of'],
  4: ['phâa', 'phaa', 'cloth, fabric'],
  5: ['nǎŋ', 'nang', 'leather'],
  6: ['phláatsatìk', 'phlaatsatik', 'plastic'],
  7: ['khláykhláay kàp', 'khlaykhlaay kap', 'to be similar, to resemble'],
  8: ['də̄ənthāaŋ', 'deenthaang', 'to travel'],
  9: ["'āachîip", 'aachiip', 'occupation'],
  10: ['sùanmâak', 'suanmaak', 'mostly, majority'],
  11: ['mǎaykhwāam wâa', 'maaykhwaam waa', 'mean'],
  12: ['rúusʉ̀k', 'ruusuk', 'to feel'],
  13: ['yāŋŋíi', 'yangngii', 'like this'],
  14: ['thùuktɔ̂ŋ (thùuk)', 'thuuktong (thuuk)', 'to be correct'],
};

